### ISSUE TITLE
PersistentVector can't handle reverse iteration starting from last element

### ISSUE THREAD

**Issue by pniederw** [GlenKPeterson/UncleJim#8]
If `index == size()`, then `array = null`, and `previous()` will throw NPE.

Also, `listIterator()` doesn't do any bounds checks (unlike `UnmodList.listIterator()`).

**Comment by GlenKPeterson** [comment]
Thank you!  This is fixed in 1.0.3 which has been deployed to Maven.  Also as a result of this, I greatly improved the tests for listIterator and found and fixed bugs in RangeOfInt and UnmodList.  You can see details and your credit in the [change log](https://github.com/GlenKPeterson/UncleJim/blob/master/changeLog.md) (and in the diff).
